# Generated by Django 2.1.7 on 2019-04-01 03:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chooseyouradventure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='code',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
