# Generated by Django 2.1.7 on 2019-04-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chooseyouradventure', '0002_auto_20190401_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='code',
            field=models.TextField(help_text='Add your game code here', null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(help_text='Pick a snazzy title', max_length=100),
        ),
        migrations.AlterField(
            model_name='game',
            name='url',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
