# Generated by Django 2.1.7 on 2019-04-05 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chooseyouradventure', '0003_auto_20190404_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='user',
            field=models.CharField(default='Anonymous', max_length=255),
        ),
    ]
